const englishCurrencyNames = {
  "afn-afghan-afghani": "afghan afghani",
  "all-albanian-lek": "albanian lek",
  "dzd-algerian-dinar": "algerian dinar",
  "aoa-angolan-kwanza": "angolan kwanza",
  "ars-argentine-peso": "argentine peso",
  "amd-armenian-dram": "armenian dram",
  "awg-aruban-or-dutch-guilder": "aruban guilder",
  "aud-australian-dollar": "australian dollar",
  "azn-azerbaijan-manat": "azerbaijan manat",
  "bsd-bahamian-dollar": "bahamian dollar",
  "bhd-bahraini-dinar": "bahraini dinar",
  "bdt-bangladeshi-taka": "bangladeshi taka",
  "bbd-barbadian-or-bajan-dollar": "barbadian dollar",
  "lsl-basotho-loti": "basotho loti",
  "byr-belarusian-ruble": "belarusian ruble",
  "byn-belarusian-ruble": "belarusian ruble",
  "bzd-belizean-dollar": "belizean dollar",
  "bmd-bermudian-dollar": "bermudian dollar",
  "btn-bhutanese-ngultrum": "bhutanese ngultrum",
  "xbt-bitcoin": "bitcoin",
  "bob-bolivian-bolíviano": "bolivian bolíviano",
  "bam-bosnian-convertible-mark": "bosnian mark",
  "bwp-botswana-pula": "botswana pula",
  "brl-brazilian-real": "brazilian real",
  "gbp-british-pound": "british pound",
  "bnd-bruneian-dollar": "bruneian dollar",
  "bgn-bulgarian-lev": "bulgarian lev",
  "mmk-burmese-kyat": "burmese kyat",
  "bif-burundian-franc": "burundian franc",
  "cad-canadian-dollar": "canadian dollar",
  "khr-cambodian-riel": "cambodian riel",
  "cve-cape-verdean-escudo": "cape verdean escudo",
  "kyd-caymanian-dollar": "caymanian dollar",
  "xaf-central-african-cfa-franc-beac": "central african franc",
  "xpf-cfp-franc": "cfp franc",
  "xof-cfa-franc": "cfa franc",
  "clp-chilean-peso": "chilean peso",
  "cny-chinese-yuan-renminbi": "chinese yuan renminbi",
  "cop-colombian-peso": "colombian peso",
  "kmf-comorian-franc": "comorian franc",
  "cdf-congolese-franc": "congolese franc",
  "crc-costa-rican-colon": "costa rican colon",
  "hrk-croatian-kuna": "croatian kuna",
  "cuc-cuban-convertible-peso": "cuban peso",
  "cup-cuban-peso": "cuban peso",
  "czk-czech-koruna": "czech koruna",
  "dkk-danish-krone": "danish krone",
  "djf-djiboutian-franc": "djiboutian franc",
  "dop-dominican-peso": "dominican peso",
  "ang-dutch-guilder": "dutch guilder",
  "xcd-east-caribbean-dollar": "east caribbean dollar",
  "egp-egyptian-pound": "egyptian pound",
  "aed-emirati-dirham": "emirati dirham",
  "ern-eritrean-nakfa": "eritrean nakfa",
  "eek-estonian-kroon": "estonian kroon",
  "etb-ethiopian-birr": "ethiopian birr",
  "eur-euro": "euro",
  "fjd-fijian-dollar": "fijian dollar",
  "fkp-falkland-island-pound": "falkland island pound",
  "gmd-gambian-dalasi": "gambian dalasi",
  "gel-georgian-lari": "georgian lari",
  "ghs-ghanaian-cedi": "ghanaian cedi",
  "gip-gibraltar-pound": "gibraltar pound",
  "xau-gold-ounce": "gold ounce",
  "gtq-guatemalan-quetzal": "guatemalan quetzal",
  "ggp-guernsey-pound": "guernsey pound",
  "gnf-guinean-franc": "guinean franc",
  "gyd-guyanese-dollar": "guyanese dollar",
  "htg-haitian-gourde": "haitian gourde",
  "hnl-honduran-lempira": "honduran lempira",
  "hkd-hong-kong-dollar": "hong kong dollar",
  "huf-hungarian-forint": "hungarian forint",
  "isk-icelandic-krona": "icelandic krona",
  "inr-indian-rupee": "indian rupee",
  "idr-indonesian-rupiah": "indonesian rupiah",
  "imp-isle-of-man-pound": "isle-of-man pound",
  "ils-israeli-shekel": "israeli shekel",
  "irr-iranian-rial": "iranian rial",
  "iqd-iraqi-dinar": "iraqi dinar",
  "jmd-jamaican-dollar": "jamaican dollar",
  "jpy-japanese-yen": "japanese yen",
  "jep-jersey-pound": "jersey pound",
  "jod-jordanian-dinar": "jordanian dinar",
  "kzt-kazakhstani-tenge": "kazakhstani tenge",
  "kes-kenyan-shilling": "kenyan shilling",
  "kwd-kuwaiti-dinar": "kuwaiti dinar",
  "kgs-kyrgyzstani-som": "kyrgyzstani som",
  "lak-lao-kip": "lao kip",
  "lvl-latvian-lat": "latvian lat",
  "lbp-lebanese-pound": "lebanese pound",
  "lyd-libyan-dinar": "libyan dinar",
  "lrd-liberian-dollar": "liberian dollar",
  "ltl-lithuanian-litas": "lithuanian litas",
  "mwk-malawian-kwacha": "malawian kwacha",
  "mvr-maldivian-rufiyaa": "maldivian rufiyaa",
  "myr-malaysian-ringgit": "malaysian ringgit",
  "mop-macau-pataca": "macau pataca",
  "mkd-macedonian-denar": "macedonian denar",
  "mga-malagasy-ariary": "malagasy ariary",
  "mro-mauritanian-ouguiya": "mauritanian ouguiya",
  "mru-mauritanian-ouguiya": "mauritanian ouguiya",
  "mur-mauritian-rupee": "mauritian rupee",
  "mxn-mexican-peso": "mexican peso",
  "mdl-moldovan-leu": "moldovan leu",
  "mnt-mongolian-tughrik": "mongolian tughrik",
  "mad-moroccan-dirham": "moroccan dirham",
  "mzn-mozambican-metical": "mozambican metical",
  "nad-namibian-dollar": "namibian dollar",
  "npr-nepalese-rupee": "nepalese rupee",
  "nzd-new-zealand-dollar": "new zealand dollar",
  "nio-nicaraguan-cordoba": "nicaraguan cordoba",
  "ngn-nigerian-naira": "nigerian naira",
  "kpw-north-korean-won": "north korean won",
  "nok-norwegian-krone": "norwegian krone",
  "omr-omani-rial": "omani rial",
  "pkr-pakistani-rupee": "pakistani rupee",
  "xpd-palladium-ounce": "palladium ounce",
  "pab-panamanian-balboa": "panamanian balboa",
  "pgk-papua-new-guinean-kina": "papua new guinean kina",
  "pyg-paraguayan-guarani": "paraguayan guarani",
  "pen-peruvian-sol": "peruvian sol",
  "php-philippine-peso": "philippine peso",
  "xpt-platinum-ounce": "platinum ounce",
  "pln-polish-zloty": "polish zloty",
  "qar-qatari-riyal": "qatari riyal",
  "ron-romanian-leu": "romanian leu",
  "rub-russian-ruble": "russian ruble",
  "rwf-rwandan-franc": "rwandan franc",
  "shp-saint-helenian-pound": "saint helenian pound",
  "svc-salvadoran-colon": "salvadoran colon",
  "wst-samoan-tala": "samoan tala",
  "stn-sao-tomean-dobra": "sao tomean dobra",
  "std-sao-tomean-dobra": "sao tomean dobra",
  "sar-saudi-arabian-riyal": "saudi arabian riyal",
  "spl-seborgan-luigino": "seborgan luigino",
  "rsd-serbian-dinar": "serbian dinar",
  "scr-seychellois-rupee": "seychellois rupee",
  "sll-sierra-leonean-leone": "sierra leonean leone",
  "xag-silver-ounce": "silver ounce",
  "sgd-singapore-dollar": "singapore dollar",
  "sbd-solomon-islander-dollar": "solomon islander dollar",
  "sos-somali-shilling": "somali shilling",
  "zar-south-african-rand": "south african rand",
  "krw-south-korean-won": "south korean won",
  "xdr-imf-special-drawing-rights": "special drawing rights",
  "lkr-sri-lankan-rupee": "sri lankan rupee",
  "sdg-sudanese-pound": "sudanese pound",
  "srd-surinamese-dollar": "surinamese dollar",
  "szl-swazi-lilangeni": "swazi lilangeni",
  "sek-swedish-krona": "swedish krona",
  "chf-swiss-franc": "swiss franc",
  "syp-syrian-pound": "syrian pound",
  "twd-taiwan-new-dollar": "taiwan new dollar",
  "tjs-tajikistani-somoni": "tajikistani somoni",
  "tzs-tanzanian-shilling": "tanzanian shilling",
  "thb-thai-baht": "thai baht",
  "top-tongan-pa'anga": "tongan pa'anga",
  "ttd-trinidadian-dollar": "trinidadian dollar",
  "tnd-tunisian-dinar": "tunisian dinar",
  "try-turkish-lira": "turkish lira",
  "tmt-turkmenistani-manat": "turkmenistani manat",
  "tvd-tuvaluan-dollar": "tuvaluan dollar",
  "ugx-ugandan-shilling": "ugandan shilling",
  "uah-ukrainian-hryvnia": "ukrainian hryvnia",
  "uyu-uruguayan-peso": "uruguayan peso",
  "usd-us-dollar": "us dollar",
  "uzs-uzbekistani-som": "uzbekistani som",
  "vuv-ni-vanuatu-vatu": "vanuatu vatu",
  "ves-venezuelan-bolívar": "venezuelan bolívar",
  "veb-venezuelan-bolívar": "venezuelan bolívar",
  "vef-venezuelan-bolívar": "venezuelan bolívar",
  "vnd-vietnamese-dong": "vietnamese dong",
  "yer-yemeni-rial": "yemeni rial",
  "zmw-zambian-kwacha": "zambian kwacha",
  "zmk-zambian-kwacha": "zambian kwacha",
  "zwd-zimbabwean-dollar": "zimbabwean dollar",
};

export default englishCurrencyNames;
