const hebrewCurrencyNames = {
  "ugx-ugandan-shilling": "שילינג אוגנדה",
  "uzs-uzbekistani-som": "סום אוזבקי",
  "aud-australian-dollar": "דולר אוסטרלי",
  "uyu-uruguayan-peso": "פזו אורוגוואי",
  "uah-ukrainian-hryvnia": "גריבנה אוקראינית",
  "azn-azerbaijan-manat": "מנט אזרבייג'ני",
  "sbd-solomon-islander-dollar": "דולר איי סולומון",
  "scr-seychellois-rupee": "רופי איי סיישל",
  "kyd-caymanian-dollar": "דולר איי קיימן",
  "idr-indonesian-rupiah": "רופי אינדונזי",
  "isk-icelandic-krona": "קרונה איסלאנדית",
  "irr-iranian-rial": "ריאל איראני",
  "eur-euro": "אירו",
  "all-albanian-lek": "לק אלבני",
  "dzd-algerian-dinar": "דינאר אלג'ירי",
  "aed-emirati-dirham": "דירהם אמירויות",
  "usd-us-dollar": "דולר אמריקאי",
  "aoa-angolan-kwanza": "קוואנזה אנגולי",
  "eek-estonian-kroon": "קרון אסטוני",
  "afn-afghan-afghani": "אפגני אפגניסטאני",
  "ars-argentine-peso": "פזו ארגנטינאי",
  "awg-aruban-or-dutch-guilder": "גילדר ארובה",
  "ern-eritrean-nakfa": "נקפה אריתראי",
  "amd-armenian-dram": "דראם ארמני",
  "etb-ethiopian-birr": "ביר אתיופי",
  "btn-bhutanese-ngultrum": "נגולטרום בהוטני",
  "bgn-bulgarian-lev": "לב בולגריה",
  "bob-bolivian-bolíviano": "בוליביאני בוליביה",
  "bam-bosnian-convertible-mark": "מארק בוסני",
  "bwp-botswana-pula": "פולה בוצוואני",
  "bif-burundian-franc": "פרנק בורונדי",
  "mmk-burmese-kyat": "קיאט בורמזי",
  "bhd-bahraini-dinar": "דינאר בחריין",
  "xbt-bitcoin": "ביטקוין",
  "byr-belarusian-ruble": "רובל בלארוסי",
  "byn-belarusian-ruble": "רובל בלארוסי",
  "bzd-belizean-dollar": "דולר בליז",
  "bdt-bangladeshi-taka": "טאקה בנגלדשי",
  "lsl-basotho-loti": "לוטי בסוטו",
  "bbd-barbadian-or-bajan-dollar": "דולר ברבדוס",
  "bnd-bruneian-dollar": "דולר ברונאי",
  "brl-brazilian-real": "ריאל ברזילאי",
  "bmd-bermudian-dollar": "דולר ברמודה",
  "gel-georgian-lari": "לרי גאורגיה",
  "gtq-guatemalan-quetzal": "קואצל גוואטאמלי",
  "ggp-guernsey-pound": "פאונד גורנזי",
  "gyd-guyanese-dollar": "דולר גיאני",
  "gip-gibraltar-pound": "פאונד גיברלטר",
  "gnf-guinean-franc": "פראנק גיניאה",
  "gmd-gambian-dalasi": "דאלאסי גמביה",
  "jmd-jamaican-dollar": "דולר ג'מייקאני",
  "ghs-ghanaian-cedi": "סדי גנאי",
  "jep-jersey-pound": " ג'רזי פאונד",
  "djf-djiboutian-franc": "פראנק דג'יבוטי",
  "dop-dominican-peso": "פזו דומיניקני",
  "dkk-danish-krone": "קרונה דנמרק",
  "zar-south-african-rand": "רנד דרום אפריקה",
  "krw-south-korean-won": "וון דרום קוריאני",
  "imp-isle-of-man-pound": "פאונד האי מאן ",
  "htg-haitian-gourde": "גווארד האיטי",
  "bsd-bahamian-dollar": "דולר האיים הבהמיים",
  "mvr-maldivian-rufiyaa": "רופייה האיים המלדיבים",
  "inr-indian-rupee": "רופי הודי",
  "ang-dutch-guilder": "גילדר הולנדי",
  "hkd-hong-kong-dollar": "דולר הונג קונג",
  "huf-hungarian-forint": "פורינט הונגרי",
  "hnl-honduran-lempira": "למפירה הונדורס",
  "vnd-vietnamese-dong": "דונג ויאטנמי",
  "vuv-ni-vanuatu-vatu": "ואטו ונואטו",
  "vef-venezuelan-bolívar": "בוליבר ונצואליאני",
  "veb-venezuelan-bolívar": "בוליבר ונצואליאני",
  "ves-venezuelan-bolívar": "בוליבר ונצואליאני",
  "xau-gold-ounce": "אונקיית זהב",
  "xdr-imf-special-drawing-rights": "זכויות משיכה מיוחדות",
  "zwd-zimbabwean-dollar": "דולר זימבבואה",
  "zmw-zambian-kwacha": "קאווצ'ה זמביה",
  "zmk-zambian-kwacha": "קוואצ'ה זמביה",
  "tjs-tajikistani-somoni": "סומוני טג'יקיסטאני",
  "tvd-tuvaluan-dollar": "דולר טובאלו",
  "top-tongan-pa'anga": "פאנגה טונגן",
  "try-turkish-lira": "לירה טורקית",
  "tmt-turkmenistani-manat": "מנט טורקמיניסטאני",
  "twd-taiwan-new-dollar": "דולר חדש טייוואני",
  "tzs-tanzanian-shilling": "שילינג טנזני",
  "ttd-trinidadian-dollar": "דולר טרינידדי",
  "jpy-japanese-yen": "ין יפני",
  "jod-jordanian-dinar": "דינאר ירדני",
  "ils-israeli-shekel": "שקל ישראלי",
  "kwd-kuwaiti-dinar": "דינאר כיוותי",
  "xag-silver-ounce": "אונקיית כסף",
  "lak-lao-kip": "קיפ לאו",
  "lbp-lebanese-pound": "פאונד לבנוני",
  "lyd-libyan-dinar": "דינאר לובי",
  "lvl-latvian-lat": "לאט לטבי",
  "lrd-liberian-dollar": "דולר ליברי",
  "ltl-lithuanian-litas": "ליטאס ליטואני",
  "mur-mauritian-rupee": "רופי מאוריטני",
  "mro-mauritanian-ouguiya": "אאוגוייה מאוריטיאני",
  "mru-mauritanian-ouguiya": "אאוגוייה מאוריטיאני",
  "mwk-malawian-kwacha": "קוואצ'ה מאלאווי",
  "mzn-mozambican-metical": "מטיקל מוזמביק",
  "mdl-moldovan-leu": "לאו מולדובי",
  "mnt-mongolian-tughrik": "טוג'ריק מונגולי",
  "xcd-east-caribbean-dollar": "דולר מזרח קאריביים",
  "mga-malagasy-ariary": "אריארי מלגסי",
  "myr-malaysian-ringgit": "רינגיט מלזי",
  "egp-egyptian-pound": "פאונד מצרי",
  "mop-macau-pataca": "פאטאקה מקאו",
  "mkd-macedonian-denar": "דנר מקדוני",
  "mxn-mexican-peso": "פזו מקסיקני",
  "mad-moroccan-dirham": "דירהם מרוקאי",
  "xpf-cfp-franc": "פרנק מרכז אפריקאי",
  "xaf-central-african-cfa-franc-beac": "פרנק מרכז אפריקאי",
  "xof-cfa-franc": "פרנק מרכז אפריקאי",
  "npr-nepalese-rupee": "רופי נאפאלי",
  "nok-norwegian-krone": "קרונה נורווגית",
  "ngn-nigerian-naira": "נאירה ניגריה",
  "nzd-new-zealand-dollar": "דולר ניו זילנדי",
  "nio-nicaraguan-cordoba": "קורדובה ניקראגאווה",
  "nad-namibian-dollar": "דולר נמיביה",
  "stn-sao-tomean-dobra": "דוברה סאו טומאן",
  "std-sao-tomean-dobra": "דוברה סאו טומאן",
  "spl-seborgan-luigino": "לואיגינו סבורגני",
  "sdg-sudanese-pound": "פאונד סודאני",
  "szl-swazi-lilangeni": "לילנגני סווזי",
  "sos-somali-shilling": "שילינג סומלי",
  "syp-syrian-pound": "פאונד סורי",
  "srd-surinamese-dollar": "דולר סורינאמי",
  "shp-saint-helenian-pound": "פאונד סיינט הלנה",
  "sll-sierra-leonean-leone": "לאונה סיירה לאון",
  "sgd-singapore-dollar": "דולר סינגפורי",
  "cny-chinese-yuan-renminbi": "יואן סיני",
  "svc-salvadoran-colon": "קולון סלבדורי",
  "wst-samoan-tala": "טאלה סמואה",
  "rsd-serbian-dinar": "דולר סרבי",
  "lkr-sri-lankan-rupee": "רופי סרי לנקה",
  "omr-omani-rial": "ריאל עומני",
  "iqd-iraqi-dinar": "דינר עיראקי",
  "sar-saudi-arabian-riyal": "ריאל ערב הסעודית",
  "pyg-paraguayan-guarani": "גוארני פאראגוואי",
  "pln-polish-zloty": "זלוטי פולני",
  "fkp-falkland-island-pound": "פאונד פולקלנד",
  "fjd-fijian-dollar": "דולר פ'יגי",
  "php-philippine-peso": "פזו פיליפינים",
  "xpd-palladium-ounce": " אונקיית פלדיום",
  "xpt-platinum-ounce": "אונקיית פלטיניום",
  "pab-panamanian-balboa": "בלבואה פנמה",
  "pgk-papua-new-guinean-kina": "קינה פפואה ניו גיני",
  "pen-peruvian-sol": "סול פרואני",
  "pkr-pakistani-rupee": "רופי פקיסטני",
  "clp-chilean-peso": "פזו צ'יליאני",
  "czk-czech-koruna": "קורונה צ'כית",
  "kpw-north-korean-won": "וון צפון קוריאני",
  "qar-qatari-riyal": "ריאל קאטארי",
  "cup-cuban-peso": "פזו קובני",
  "cuc-cuban-convertible-peso": "פזו קובני מומר",
  "kmf-comorian-franc": "פראנק קומורוס",
  "cop-colombian-peso": "פזו קולומביאני",
  "cdf-congolese-franc": "פרנק קונגולזי",
  "crc-costa-rican-colon": "קולון קוסטה-ריקני",
  "kzt-kazakhstani-tenge": "טנגה קזאחסטאני",
  "cve-cape-verdean-escudo": "אסקודו קייפ ורדה",
  "kgs-kyrgyzstani-som": "סום קירגיסטאני",
  "khr-cambodian-riel": "רייל קמבודי",
  "cad-canadian-dollar": "דולר קנדי",
  "kes-kenyan-shilling": "שילינג קנייתי",
  "hrk-croatian-kuna": "קונה קרואטי",
  "rwf-rwandan-franc": "פרנק ראוונדי",
  "ron-romanian-leu": "לאו רומני",
  "rub-russian-ruble": "רובל רוסי",
  "sek-swedish-krona": "קרונה שבדית",
  "chf-swiss-franc": "פרנק שוויצרי",
  "gbp-british-pound": "לירה שטרלינג",
  "thb-thai-baht": "באט תאילנדי",
  "tnd-tunisian-dinar": "דינאר תוניסאי",
  "yer-yemeni-rial": "ריאל תימן",
};

export default hebrewCurrencyNames;
